# syntax = docker/dockerfile:1.3

FROM alpine
RUN apk add --no-cache openssh-client git
RUN apk add nodejs npm
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh git clone git@github.com:GrzegorzBielesza/Lab1Cloud.git
RUN echo $(ssh-add -l) && echo $SSH_AUTH_SOCK
WORKDIR Lab1Cloud
RUN npm install
EXPOSE 8080
CMD ["npm", "start"]